### ISSUE TITLE
Cannot Create System.Drawing.Font to pass to Graphics.DrawString() on OS X

### ISSUE THREAD

**Issue by cbright** [CoreCompat/CoreCompat#10]
I'm trying to draw text onto an image on OS X Sierra dotnet core 1.1. I cannot successfully create an instance of System.Drawing.Font.

```
System.ArgumentException: The requested FontFamily could not be found [GDI+ status: FontFamilyNotFound]
   at System.Drawing.GDIPlus.CheckStatus(Status status)
   at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
   at System.Drawing.FontFamily.get_GenericSansSerif()
```

I've tried various permutations which all result in the a similar error.

```
var headerFont = new Font(FontFamily.GenericSansSerif, 16f);
var headerFont2 = new Font("Arial", 16f);
var familes = FontFamily.Families;
```

In the last, example as well as calling `FontFamily.GetFamilies()`, results in an empty array.

**Comment by Howard-ThinkGeo** [comment]
I'm having the same issue. Is there any update?

**Comment by qmfrederik** [comment]
Hi guys,

If you can, can you give this a try on .NET Core 2.0 (preview) and the [CoreCompat.System.Drawing.v2](https://github.com/CoreCompat/System.Drawing) package?

**Comment by Howard-ThinkGeo** [comment]
Sure, I will give it a shot later when I’m back to office. Let you know then.

Thanks,
Howard

**Comment by TarasKovalenko** [comment]
The issue still present in the latest version:
```
An unhandled exception occurred while processing the request.
ArgumentException: The requested FontFamily could not be found [GDI+ status: FontFamilyNotFound]
System.Drawing.GDIPlus.CheckStatus(Status status)
```
```
ArgumentException: The requested FontFamily could not be found [GDI+ status: FontFamilyNotFound]
System.Drawing.GDIPlus.CheckStatus(Status status)
System.Drawing.FontFamily.get_GenericSansSerif()
System.Drawing.Font.CreateFont(string familyName, float emSize, FontStyle style, GraphicsUnit unit, byte charSet, bool isVertical)
System.Drawing.Font..ctor(string familyName, float emSize, FontStyle style, GraphicsUnit unit)
```
Any idea how to fix that?
