### ISSUE TITLE
"GDI+ status: InvalidParameter" when creating Bitmap from Stream

### ISSUE THREAD

**Issue by callebjernekull** [CoreCompat/CoreCompat#16]
I'm reading image-files from a blob and want to create them from the stream like this:
using (Stream stream = await blob.OpenReadAsync())
{
   bitmap = new Bitmap(stream);          
}
This seems to work at this point, but I want to use this bitmap and draw it in another bitmap with graphics:
graphics.DrawImage(bitmap, destRect, 0, 0, bitmap.Width, bitmap.Height, GraphicsUnit.Pixel);

This will give me this error:
The operation is invalid [GDI+ status: Win32Error]
   at System.Drawing.GDIPlus.CheckStatus(Status status)
   at System.Drawing.Graphics.DrawImage(Image image, Rectangle destRect, Int32 srcX, Int32 srcY, Int32 srcWidth, Int32 srcHeight, GraphicsUnit srcUnit, ImageAttributes imageAttr)

**Workaround**
But I also found something when debugging. If I get bitmap.Palette, it will throw this exception:
A null reference or invalid value was found [GDI+ status: InvalidParameter]
   at System.Drawing.GDIPlus.CheckStatus(Status status)
   at System.Drawing.Image.retrieveGDIPalette()
   at System.Drawing.Image.get_Palette()

unless I call bitmap.Palette while stream is open. This is also a workaround for this issue:
Bitmap bitmap;   
using (Stream stream = await blob.OpenReadAsync())
{
   bitmap = new Bitmap(stream);
   var palette = bitmap.Palette; //I don't use Palette for anything, just getting it and the rest will work
}

**Comment by avi-s** [comment]
Any updates on this issue?

I'm getting "A null reference or invalid value was found [GDI+ status: InvalidParameter]" upon saving a Bitmap.

Thanks

**Comment by qmfrederik** [comment]
Can you check whether this works with the System.Drawing.Common NuGet package?

**Comment by avi-s** [comment]
@qmfrederik Thanks a lot man.
I didn't know they have released that package. That solved the problem.

**Comment by SaddamBInSyed** [comment]
@qmfrederik , Hi there, Could you please explain how it can solve the pbm? since I am facing the same issue while setting the image to my PictureBox in raspbian stretch using C# Mono.
