### ISSUE TITLE
Error getting font handle

### ISSUE THREAD

**Issue by zparrish** [CoreCompat/CoreCompat#2]
I'm trying to use your library in order to update a separate PDF library to work with .NET Core and I've run into an issue with fonts, specifically getting a font handle. When calling ToHFont() on a Font object:

```
var font = new System.Drawing.Font("Arial", 10);
var hfont = font.ToHfont();
```

I receive the following error:

```
System.ArgumentException: Object contains non-primitive or non-blittable data.
   at System.Runtime.InteropServices.GCHandle.InternalAlloc(Object value, GCHandleType type)
   at System.Runtime.InteropServices.GCHandle..ctor(Object value, GCHandleType type)
   at System.Runtime.InteropServices.GCHandle.Alloc(Object value, GCHandleType type)
   at System.Drawing.Font.ToLogFont(Object logFont, Graphics graphics)
   at System.Drawing.Font.ToLogFont(Object logFont)
   at System.Drawing.Font.ToHfont()
```

Any help you could provide would be greatly appreciated.

Thanks

**Comment by qmfrederik** [comment]
Hi @zparrish,

Thanks for giving the library a try & sorry to hear you're running into trouble.

I would need to dive a bit deeper into this to provide a fix, it's probably related to how fonts are marshalled. I may have some time over the weekend to look into this.

In meanwhile, should you want to give it a try and troubleshoot it yourself, #1 has some instructions on how to compile from source.

Sorry for the delay & will get back to you,

**Comment by qmfrederik** [comment]
Hi @zparrish 

Almost a year later :), there's an updated version of System.Drawing for .NET Core which supports .NET Core 2.0 and I was wondering whether you could give this a try on .NET Core 2.0?

If so, please use the [CoreCompat.System.Drawing.v2](https://github.com/CoreCompat/System.Drawing) package and let me know how it goes.

Thanks!
