### ISSUE TITLE
Unable to load DLL 'gdiplus'

### ISSUE THREAD

**Issue by judypol** [CoreCompat/CoreCompat#3]
Hi 

I use the CoreCompat.System.Drawing in centOs7.1 and I  reference the runtime.linux-x64.CoreCompat.System.Drawing,then Get the Unable to load DLL 'gdiplus' error.

**Comment by qmfrederik** [comment]
@judypol

This is probably because of a missing dependency on CentOS 7.1

Can you try to run your program with the `LD_DEBUG` variable set to `libs` and share the output?

E.g.:

```
$ export LD_DEBUG=libs
$ dotnet run
```

Alternatively, you can try to build your own version of the `runtime.linux-x64.CoreCompat.System.Drawing` package by cloning this repository, navigating to the `native/runtime.linux-x64.CoreCompat.System.Drawing` folder and running `./get-sources.sh`, `./build.sh` and `dotnet pack`.

**Comment by CAH-FlyChen** [comment]
after install  libgdiplus 。works fine。

**Comment by DeokJae** [comment]
I use the CoreCompat.System.Drawing in centOs7.1.
----------------------------------------------------------------------------------------------------------------
System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdiplus': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at System.Drawing.GDIPlus.GdiplusStartup(UInt64& token, GdiplusStartupInput& input, GdiplusStartupOutput& output)
   at System.Drawing.GDIPlus..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.GDIPlus.RunningOnUnix()
   at System.Drawing.Image.InitFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)

what is problem??

**Comment by judypol** [comment]
@CAH-FlyChen can you help me install the libgdiplus in CentOS 7.1

thanks!

**Comment by judypol** [comment]
@qmfrederik in centos7 I installed the libgdiplus,but I got the below error:
Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdiplus': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at System.Drawing.GDIPlus.GdiplusStartup(UInt64& token, GdiplusStartupInput& input, GdiplusStartupOutput& output)
   at System.Drawing.GDIPlus..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.GDIPlus.GdipLoadImageFromFile(String filename, IntPtr& image)
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at System.Drawing.Image.FromFile(String filename)
   at ConsoleApplication.Program.Main(String[] args)
and run find / -name 'libgdiplus*',the result is below:
/usr/local/lib/pkgconfig/libgdiplus.pc
/usr/local/lib/libgdiplus.so.0.0.0
/usr/local/lib/libgdiplus.so.0
/usr/local/lib/libgdiplus.so
/usr/local/lib/libgdiplus.la
/usr/local/lib/libgdiplus.a

but in Ubuntu16 is Ok.
do you can help me.?

**Comment by tanaka-takayoshi** [comment]
Hello, I got the same error on Red Hat Enterprise Linux 7.2.

**Comment by donnytang** [comment]
@judypol , I am got that error in CentOS too, have you find the way to resove it?

**Comment by judypol** [comment]
@donnytang ,no ,I used this in Ubuntu14.04.it Ok.

**Comment by jasonsturges** [comment]
Likewise on Mac OS X, libgdiplus not found

```
Exception thrown: 'System.TypeInitializationException' in CoreCompat.System.Drawing.dll
Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdiplus': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at System.Drawing.GDIPlus.GdiplusStartup(UInt64& token, GdiplusStartupInput& input, GdiplusStartupOutput& output)
   at System.Drawing.GDIPlus..cctor()
```

Unfortunate this requires a build of libgdiplus.so

**Comment by qmfrederik** [comment]
@jasonsturges Can you try to add a reference to `runtime.osx.10.10-x64.CoreCompat.System.Drawing` (https://www.nuget.org/packages/runtime.osx.10.10-x64.CoreCompat.System.Drawing/1.0.1-beta004)? This should copy over the required dependencies for macOS.

That said, given the number of people reporting issues with this, I'll update the library to include the native libraries, too, once we ship a new version (which should be when netstandard 2.0 ships)

**Comment by pucis** [comment]
Had the same problem on CentOS 7.
In my case there was some problem with included libgdiplus.so
Solved by removing ./runtimes/linux-x64/native/libgdiplus.so
and repaced with link to system file:
` ln -s /usr/lib64/libgdiplus.so.0.0.0 ./runtimes/linux-x64/native/libgdiplus.so`

Used:
CoreCompat.System.Drawing 1.0.0-beta006
runtime.linux-x64.CoreCompat.System.Drawing 1.0.0-beta009

**Comment by jasonsturges** [comment]
@qmfrederik It works perfectly with added reference: 

[`runtime.osx.10.10-x64.CoreCompat.System.Drawing`](https://www.nuget.org/packages/runtime.osx.10.10-x64.CoreCompat.System.Drawing/1.0.1-beta004)

This also resolves my antialias problem with image resizing from issue #8 

By the way, at runtime that library is displaying a warning: `Fontconfig error: Cannot load default config file`

**Comment by ugumba** [comment]
I get the same error when running in a Docker for Windows container (running the default Hyper-V MobyLinux host).  
Now, Docker reports the OSType as "linux", and I see that the native runtimes are present only in the "publish\runtimes\linux-x64" folder.  (That connection is a pure leap of faith - I'm treading deep waters here!)  
I think I'll put Linux aside for the moment, and deploy to Nano Server instead.

**Comment by BogdanovKirill** [comment]
The problem is that core clr doesn't have dll mapping mechanism like MONO. So, look at here:
https://github.com/qmfrederik/mono/blob/ea0b1d6059e3fe1f7988c5a4689bf6431b0a3ad7/mcs/class/System.Drawing/System.Drawing/gdipFunctions.cs#L61
We always try to load "gdiplus.dll". Also I want to add that fix like "gdiplus" will not work. See discussion about dllmap:
https://github.com/dotnet/coreclr/issues/930
So, we should find solution.

**Comment by qmfrederik** [comment]
That's not entirely correct, the branch from which System.Drawing is built has an updated [gdipFunctions.cs](https://github.com/qmfrederik/mono/blob/coreclr/system.drawing/mcs/class/System.Drawing/System.Drawing/gdipFunctions.cs) where the P/Invoke is done to `gdiplus`. This has also recently been changed in Mono.

So as long as you have `libgdiplus.so` in one of the paths set in the LD_LIBRARY_PATH, this should work.

Normaly linux-x64 should work, if not, try installing libgdiplus from your Linux distribution.

**Comment by qmfrederik** [comment]
Here's what it looks like in upstream Mono now : [gdipFunctions.cs](https://github.com/mono/mono/blob/master/mcs/class/System.Drawing/System.Drawing/gdipFunctions.cs)

**Comment by BogdanovKirill** [comment]
Sorry, I was wrong. I've check it on Ubuntu and all is ok. The solution for docket is:
RUN apt-get update
RUN apt-get install -y libgdiplus
It seems to be ugly but now my programs works! Also in console i see that errors:
Unable to update the static FcBlanks: 0x0600
Unable to update the static FcBlanks: 0x0601
Unable to update the static FcBlanks: 0x0602
Unable to update the static FcBlanks: 0x0603
Unable to update the static FcBlanks: 0x06dd
Unable to update the static FcBlanks: 0x070f
Unable to update the static FcBlanks: 0x2028
Unable to update the static FcBlanks: 0x2029
Unable to update the static FcBlanks: 0xfff9
Unable to update the static FcBlanks: 0xfffa
Unable to update the static FcBlanks: 0xfffb

**Comment by iplitt** [comment]
I have the same problem when deploying an AWS Lambda function which uses the NuGet package "CoreCompat.System.Drawing": "1.0.0-beta006".  Is there another NuGet package which supports drawing graphics without resorting to GDI?

**Comment by jasonsturges** [comment]
@iplitt Presumably you need to include the [Linux Native Libraries](https://www.nuget.org/packages/runtime.linux-x64.CoreCompat.System.Drawing/1.0.0-beta009) NuGet package?

    runtime.linux-x64.CoreCompat.System.Drawing -Version 1.0.0-beta009 -Pre

**Comment by LPAMNijoel** [comment]
May I ask a quick question? is corecompact libs compatible with ARM processor? to deploy on the raspberry pi?

**Comment by qmfrederik** [comment]
@LPAMNijoel The package itself is CPU-independent, but it requires libgdiplus to be available which needs to be compiled for ARM.

Most ARM editions of Linux distributions include libgdiplus; so as long as you install libgdiplus all should be fine.

**Comment by LPAMNijoel** [comment]
@qmfrederik  that makes sense. However, I did some googling and found out it's compatible with Debian(rasp OS) but not win IoT? see link -> https://pkgs.org/download/libgdiplus so, my main question now, is core-compact compatible with winIOT projects? the project I'm working on is a winIOT project, I'm using corecompact libs but, I failed to realize that this dll won't load on deployment to the pi im working on. any advice @qmfrederik?

**Comment by qmfrederik** [comment]
@LPAMNijoel I'm not that familiar with WinIOT, but does it include the `C:\Windows\System32\Gdiplus.dll` file? If so, you shouldn't need libgdiplus - that's just an implementation of gdiplus.dll for Linux and macOS.

Let me know if you have any issues running this on WinIOT; if so, please include the exception message and stack trace. Thanks!

**Comment by xirsoi** [comment]
Any chance getting this taken care of could be fast tracked? It's been almost 6 months since the issue was reported.

**Comment by qmfrederik** [comment]
@xirsoi In most cases, installing libgdiplus from your Linux distribution should solve this issue.

That said, .NET Core will soon (I think it's planned for version 2.1) include a version of System.Drawing for .NET Core, so that would be the final fix for this.

**Comment by xirsoi** [comment]
@qmfrederik Awesomesauce

**Comment by mythz** [comment]
I got this error when trying to use this package with the [microsoft/aspnetcore](https://hub.docker.com/r/microsoft/aspnetcore/) runtime Docker image that the ASP.NET team recommends in their [recommended multi-stage build](https://docs.microsoft.com/en-us/dotnet/core/docker/building-net-docker-images#your-first-aspnet-core-docker-app), installing `libgdiplus` didn't work, the solution was just to go back to using the `microsoft/dotnet` image, here's a working [Dockerfile](https://github.com/NetCoreApps/Imgur/blob/master/Dockerfile), hope it helps.

**Comment by kresimirfijacko** [comment]
i have the same problem on centos
that 'runtime.linux-x64.CoreCompat.System.Drawing -Version 1.0.0-beta009 -Pre' is not working out of the box, but installing one locally on centos and then putting that one in 'runtimes/linux-64/native' instead of original one makes it work

now, how to make this parmanently so i don't have to deal with this on every deploy? 
i tried putting it in one directory and setting environment variable 'LD_LIBRARY_PATH' to that path but it doesn't work
i tried to follow documentation at [link](https://github.com/dotnet/core/blob/master/Documentation/self-contained-linux-apps.md#from-that-list-remove-standard-cc-libraries-and-libraries-that-are-available-on-all-the-target-distros) , do that i created directory 'netcoredeps' inside main folder with that library but that didn't work either

any suggestions?

**Comment by qmfrederik** [comment]
@kresimirfijacko It looks like long term (.NET Core is going to provide System.Drawing OOB) the recommendation will be for you to just install libgdiplus via yum on CentOS.

There are some glitches in the process that we're trying to iron out, hopefully this will be a smooth process in the near future.

**Comment by kresimirfijacko** [comment]
@qmfrederik 
Yes, that's what I did - i installed ligbdiplus via yum, but i need app to use that one instead of the one that gets installed in folder  'myAPP/runtimes/linux-64/native' 
at the moment i'm doing this manually (by copying right one into that folder) , but i need some better way to handle this until .NET Core provides System.Drawing out-of-the-box

**Comment by qmfrederik** [comment]
@kresimirfijacko Yes, you're right, at this moment you'd need to either symlink or copy the yum-provided files.

That said, did you try to use System.Drawing.Common? The latest version should work on CentOS.

**Comment by kresimirfijacko** [comment]
@qmfrederik 
i tried to use latest System.Drawing.Common but i can't install it since my library is targeting .NET Standard 1.6 (and it needs to be 2.0)

**Comment by ikumshyamal** [comment]
You can resovle using this link....

https://en.code-bude.net/2017/05/08/net-core-gdiplus-dll-not-found-in-linux/comment-page-1/#comment-119157

**Comment by illusiz** [comment]
I'm having the same problem when debugging .Net Core 2 API on Windows docker container.

**Comment by qmfrederik** [comment]
Hi everyone on this thread,

The long-term solution for this was dotnet/corefx#17135, but I learned today that this won't make it for .NET Core 2.1.

If you're using .NET Core and System.Drawing, would you mind voting for that issue (clicking the 'thumbs up' emoji at the issue description would o it)?

Thanks!
